# Generated by Django 4.1 on 2022-08-25 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phoneDB', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
