# Generated by Django 4.1 on 2022-08-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneDB', '0005_remove_phone_slug_alter_phone_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
